{ config, lib, pkgs, ... }:

let
  cfg = config.programs.PanchaKosha.mangowc;
  formatters = import ./lib/formatters.nix { inherit lib; };

  effectsConf = formatters.generateEffectsConfig cfg.effects;
  animationsConf = formatters.generateAnimationsConfig cfg.animations;
  scrollerConf = formatters.generateScrollerConfig cfg.scroller;
  masterStackConf = formatters.generateMasterStackConfig cfg.masterStack;
  overviewConf = formatters.generateOverviewConfig cfg.overview;
  miscConf = formatters.generateMiscConfig cfg.misc;
  inputConf = formatters.generateInputConfig cfg.input;
  appearanceConf = formatters.generateAppearanceConfig cfg.appearance;
  monitorConf = formatters.formatMonitors cfg.monitors;
  envConf = formatters.formatEnvs cfg.env;
  execConf = formatters.formatExec cfg.exec;
  execOnceConf = formatters.formatExecOnce cfg.execOnce;
  keybindsConf = formatters.formatBinds cfg.bindings;
  mousebindsConf = formatters.formatMouseBinds cfg.mouseBindings;
  windowRulesConf = formatters.formatWindowRules cfg.windowRules;
  tagRulesConf = formatters.formatTagRules cfg.tagRules;
  layerRulesConf = formatters.formatLayerRules cfg.layerRules;

  configContent = ''
    # MangoWC Configuration
    # Generated by Pancha Kosha NixOS configuration

    source = monitor.conf
    source = env.conf
    source = inputs.conf
    source = exec.conf
    source = appearance.conf
    source = effects.conf
    source = animations.conf
    source = scroller.conf
    source = master-stack.conf
    source = keybinds.conf
    source = rules.conf
    source = overview.conf
    source = misc.conf
  '';
in {
  imports = [
    ./options/animations.nix
    ./options/appearance.nix
    ./options/bindings.nix
    ./options/effects.nix
    ./options/env.nix
    ./options/exec.nix
    ./options/input.nix
    ./options/master-stack.nix
    ./options/misc.nix
    ./options/monitor.nix
    ./options/overview.nix
    ./options/scroller.nix
  ];

  options.programs.PanchaKosha.mangowc = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable the Mango window compositor";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra configuration lines to append to the config file";
    };
  };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra configuration lines to append to the config file";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.portal = {
      enable = true;
      extraPortals = [
        pkgs.xdg-desktop-portal-gtk
        pkgs.xdg-desktop-portal-wlr
      ];
      config = {
        common = {
          default = ["wlr" "gtk"];
        };
        wlroots = {
          default = ["wlr" "gtk"];
          "org.freedesktop.impl.portal.FileChooser.OpenFile" = "gtk";
          "org.freedesktop.impl.portal.FileChooser.SaveFile" = "gtk";
          "org.freedesktop.impl.portal.FileChooser.SaveFiles" = "gtk";
          "org.freedesktop.impl.portal.Screenshot" = "wlr";
          "org.freedesktop.impl.portal.ScreenCast" = "wlr";
          "org.freedesktop.impl.portal.RemoteDesktop" = "wlr";
        };
      };
    };

    environment.systemPackages = with pkgs; [
      wlr-randr
      wl-clipboard
      grim
      slurp
    ];

    environment.etc."xdg/mango/config".text = configContent;

    environment.etc."xdg/mango/effects.conf".text = effectsConf;
    environment.etc."xdg/mango/animations.conf".text = animationsConf;
    environment.etc."xdg/mango/scroller.conf".text = scrollerConf;
    environment.etc."xdg/mango/master-stack.conf".text = masterStackConf;
    environment.etc."xdg/mango/overview.conf".text = overviewConf;
    environment.etc."xdg/mango/misc.conf".text = miscConf;
    environment.etc."xdg/mango/inputs.conf".text = inputConf;
    environment.etc."xdg/mango/appearance.conf".text = appearanceConf;
    environment.etc."xdg/mango/monitor.conf".text = monitorConf;
    environment.etc."xdg/mango/env.conf".text = envConf;
    environment.etc."xdg/mango/exec.conf".text = execConf + "\n" + execOnceConf;
    environment.etc."xdg/mango/keybinds.conf".text = keybindsConf + "\n" + mousebindsConf;
    environment.etc."xdg/mango/rules.conf".text = windowRulesConf + "\n" + tagRulesConf + "\n" + layerRulesConf;
  };
}
